Iter25
antonfry/cenarius pull request #1
Opened 2023-10-29 18:06 UTC by antonfry

2023-11-08 12:03 UTC, s-shpak requested changes
1. Добавь инструкции по запуску сервиса локально. Сейчас, например, при запуске сервера я получаю такую ошибку:

```
ERRO[0000] Unable to connect to the database with: postgres://postgres:5432/cenarius_test?sslmode=disable 
FATA[0000] failed to connect to `host=postgres user=bp database=cenarius_test`: hostname resolving error (lookup postgres: no such host) 
```

В README.md должна быть последовательность команд, которую я смогу скопировать, вставить в терминал, и сервис стартанет

2. Не совсем понял, где имплементация кэша клиента?

2023-11-08 12:03 UTC, s-shpak commented on cmd/cenarius/main.go
> +func init() {
Функция `init` - плохая практика, не используй ее

2023-11-08 12:03 UTC, s-shpak commented on internal/agent/agent.go
> +func (a *agent) Shutdown() {
Почему эта функция попала в PR ?

2023-11-08 12:03 UTC, s-shpak commented on cmd/cenarius/main.go
> +type cenariusWorker interface {
Зачем этот интерфейс?

2023-11-08 12:03 UTC, s-shpak commented on cmd/cenarius/main.go
> +	worker       cenariusWorker
Почему это переменная на уровне пакета?

2023-11-08 12:03 UTC, s-shpak commented on cmd/cenarius/main.go
> +		log.Fatal(err)
log.Fatal вызовет `os.Exit`, что не позволит заимплементировать `graceful shutdown`

2023-11-08 12:03 UTC, s-shpak commented on internal/agent/agent.go
> +		log.Fatal(err)
Ошибку надо пробрасывать на самый верхний уровень

2023-11-08 12:03 UTC, s-shpak commented on internal/agent/agent.go
> +		a.logger.Fatalf("agent.sendRequest req err: %s", err.Error())
Фаталиться в глубине кода нельзя

2023-11-08 12:03 UTC, s-shpak commented on internal/agent/agent.go
> +	uri := "api/v1/user/register"
Это должно быть константой (как и другие подобные объявления)

2023-11-08 12:03 UTC, s-shpak commented on internal/model/creditCard.go
В Го файлы называются через нижние подчеркивания или через дефисы

2023-11-08 12:03 UTC, s-shpak commented on internal/model/creditCard.go
> +func (s *CreditCard) Decrypt(key, iv string) error {
Правильно ли я понимаю, что ты хочешь реализовать оконечное шифрование ? Как ты предполагаешь написать логику управления ключами (отзыв ключа, обновление и т.п.) ?

2023-11-08 12:03 UTC, s-shpak commented on internal/model/testing.go
> +func TestUser(t *testing.T) *User {
Почему логика для тестов находится в пакете с бизнес-логикой?

2023-11-08 12:03 UTC, s-shpak commented on schema.sql
> +    "user_id" int,
Все поля должны быть отмечены как `NOT NULL/NULL`. По-дефолту все поля должны быть `NOT NULL`

2023-11-08 12:03 UTC, s-shpak commented on schema.sql
1. Это надо сделать через механизм миграций
2. Почему нигде не объявлены индексы?

2023-11-14 07:00 UTC, antonfry commented
> 1. Добавь инструкции по запуску сервиса локально. Сейчас, например, при запуске сервера я получаю такую ошибку:
> 
> ```
> ERRO[0000] Unable to connect to the database with: postgres://postgres:5432/cenarius_test?sslmode=disable 
> FATA[0000] failed to connect to `host=postgres user=bp database=cenarius_test`: hostname resolving error (lookup postgres: no such host) 
> ```
> 
> В README.md должна быть последовательность команд, которую я смогу скопировать, вставить в терминал, и сервис стартанет
> 
> 2. Не совсем понял, где имплементация кэша клиента?

1. Добавлен docker compose и обновлена инструкция
2. Кеш агента добавлен

2023-11-14 07:00 UTC, antonfry commented on cmd/cenarius/main.go
> +func init() {
убрал

2023-11-14 07:02 UTC, antonfry commented on internal/agent/agent.go
> +func (a *agent) Shutdown() {
для удовлетворения интерфейса cenariusWorker

2023-11-14 07:03 UTC, antonfry commented on cmd/cenarius/main.go
> +type cenariusWorker interface {
для удобного запуска/остановки сервера и агента

2023-11-14 07:04 UTC, antonfry commented on cmd/cenarius/main.go
> +	worker       cenariusWorker
не совсем понял вопрос. Эта переменная нужна только в main.go файле, служит для  запуска/остановки сервера и агента

2023-11-14 07:04 UTC, antonfry commented on cmd/cenarius/main.go
> +		log.Fatal(err)
убрал Fatal'ы

2023-11-14 07:04 UTC, antonfry commented on internal/model/creditCard.go
переименовал

2023-11-14 07:05 UTC, antonfry commented on internal/model/creditCard.go
> +func (s *CreditCard) Decrypt(key, iv string) error {
При смене ключа - перешлифовать данные клиента в бд. На данный момент такой возможности нет

2023-11-14 07:06 UTC, antonfry commented on internal/model/testing.go
> +func TestUser(t *testing.T) *User {
Это тестовый стор для тестов, для его создания нужен доступ к внутренним переменным пакета

2023-11-14 07:07 UTC, antonfry commented on schema.sql
добавлен механизм миграций + индексы

2023-11-14 07:17 UTC, antonfry commented on schema.sql
> +    "user_id" int,
добавил not null к "секретным данным"

2023-11-14 07:40 UTC, antonfry commented on internal/agent/agent.go
> +		a.logger.Fatalf("agent.sendRequest req err: %s", err.Error())
убрал

2023-11-14 07:40 UTC, antonfry commented on internal/agent/agent.go
> +	uri := "api/v1/user/register"
вынесено в константы

2023-11-14 07:40 UTC, antonfry commented on internal/agent/agent.go
> +		log.Fatal(err)
готово

2024-01-31 14:59 UTC, merged